Feature/slug/50
SiProdZz/P6_Symfony_SnowTricks pull request #59
Opened 2020-12-12 15:57 UTC by SiProdZz

2020-12-12 15:59 UTC, SiProdZz commented
It's not finish
User have to save a figure with an unique name for an unique slug.

2020-12-21 04:52 UTC, crazymad requested changes

2020-12-21 04:52 UTC, crazymad commented on src/Controller/AddFigureController.php
> +                    ->setDate(new \DateTime())
do this in the constructor of Figure

2020-12-22 09:06 UTC, crazymad approved these changes

2020-12-22 09:06 UTC, merged