Feature/forgotpassword/57
SiProdZz/P6_Symfony_SnowTricks pull request #68
Opened 2020-12-18 23:17 UTC by SiProdZz

User forgot his password and need to create a new one.

-Use token
-Create forgotten password for send a mail to reset password (genrate token)
-Create reset password to create a new password (check token)

2020-12-21 05:01 UTC, crazymad requested changes

2020-12-21 05:01 UTC, crazymad commented on src/Controller/ForgottenPasswordController.php
> +                $this->addFlash('danger', 'Cette adresse n\'existe pas');
try to not let a user know about the existence of an address in your database, but that if the email was found he should receive an email

2020-12-21 05:01 UTC, crazymad commented on src/Controller/ForgottenPasswordController.php
> +            $url = $this->generateUrl('reset_password',['token' => $token], UrlGeneratorInterface::ABSOLUTE_URL);
handle the mailing part in a private method or a service. Your controller starts to be too long

2020-12-21 05:01 UTC, crazymad commented on src/Controller/ForgottenPasswordController.php
> +            $entityManager->persist($user);
no need to persist when you don't add a new entity in the ebb

2020-12-21 05:01 UTC, crazymad commented on src/Entity/User.php
> +    private $reset_token;
use camelCase in php(PSR 1, 2, 12) snake_case would be only for the database

2020-12-23 21:44 UTC, SiProdZz commented
I made one commit  :

-Resolve conflict

- update add flash for user who ask forgotpassword. They must not know if the mail exist already or not, just a message 'mail send if this email exist'

-Create a mail service to send a mail 'forgot password'

-Update property in entity User, reset_token  to resetToken.

remove persist to add token in database ( no need)

2020-12-27 14:53 UTC, crazymad approved these changes

2020-12-27 15:47 UTC, merged